# Site settings
title: Diego Villafuerte
description: Senior Software engineer and XR Consultant
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Diego Villafuerte
user_description: I'm a passionate Software Developer, always searching for a new opportunity. Lately, I have been immersed in the <b>DevOps</b> world working for HCL UrbanCode, a Cleveland-based Enterprise DevOps lab pioneering value stream visualization. I'm splitting my time between product development and research integrating VR/AR into our product. Outside of my full-time job I do a wide range of consulting for local businesses and non-profits. 
user_title: Software Engineer
email: diegovillafuerte1@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
