pipeline:
  name: guestbook-ci-pipeline
  identifier: guestbookcipipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: <+input>
        repoName: diegovillafuerte1.github.io
        build: <+input>
  stages:
    - stage:
        name: Build and Push Image
        identifier: build_and_push
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              image: ubuntu:22.04
              shell: Bash
          execution:
            steps:
              - step:
                  name: Generate Image Tag
                  identifier: gen_image_tag
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      cd /harness
                      IMAGE_TAG="sha-$(git rev-parse --short HEAD)"
                      echo "IMAGE_TAG=$IMAGE_TAG" >> image_tag.env
              - step:
                  name: Build and Push Docker Image
                  identifier: build_and_push_image
                  type: Run
                  spec:
                    shell: Bash
                    envVariables:
                      DOCKERHUB_USER: <+secrets.getValue("dockerhub_user")>
                      DOCKERHUB_PASS: <+secrets.getValue("dockerhub_pass")>
                    command: |
                      cd /harness
                      source image_tag.env
                      echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
                      docker build -t diegovillafuertehcl/static-site:$IMAGE_TAG .
                      docker push diegovillafuertehcl/static-site:$IMAGE_TAG
